"""Eski egzersiz adlarını kanonik katalog kimliklerine bağlayan güvenli eşlemeler.

Buraya yalnızca anlamı kesin olan eski/yeni ad varyasyonları eklenmelidir.
Belirsiz isimler yanlış PR veya grafik birleşimini engellemek için eklenmez.
"""

EXERCISE_ALIASES = {
    'dumbell bench press': 'dumbbell-bench-press',
    'dumbbell chest press': 'dumbbell-bench-press',
    'cable crossover': 'cable-cross-over',
    'cable chest fly': 'cable-cross-over',
    'pull ups': 'pull-ups-bw',
    'pull up': 'pull-ups-bw',
    'weighted pull ups': 'weighted-pull-up',
    'weighted pull up': 'weighted-pull-up',
    'barfiks': 'pull-ups-bw',
    'weighted barfiks': 'weighted-pull-up',
    'chin up': 'chin-ups-bw',
    'chin ups': 'chin-ups-bw',
    'weighted chin up': 'chin-ups-weighted',
    'dumbell shoulder press': 'dumbbell-shoulder-press',
    'dumbbell shoulder press': 'dumbbell-shoulder-press',
    'shoulder press machine': 'shoulder-press-machine',
    'bulgarian split squat': 'bulgarian-split-squad',
    'bulgarian split squats': 'bulgarian-split-squad',
    # Eski genel calf kayıtları, geriye uyumluluk için Dumbbell varyasyonuna
    # bağlanır. Yeni arayüzde genel "Calf Raises" adı gösterilmez.
    'calf raise': 'calf-raises',
    'calf raises': 'calf-raises',
    'standing calf raise': 'calf-raises',
    'dumbbell calf raise': 'calf-raises',
    'dumbbell calf raises': 'calf-raises',
    'calf raise dumbbell': 'calf-raises',
    'standing calf raise dumbbell': 'calf-raises',
    'barbell calf raise': 'standing-calf-raise-barbell',
    'barbell calf raises': 'standing-calf-raise-barbell',
    'standing calf raise barbell': 'standing-calf-raise-barbell',
    'seated calf raise': 'seated-calf-raise',
    'seated calf raises': 'seated-calf-raise',
    'tricep pushdown': 'tricep-push-down',
    'triceps push down': 'tricep-push-down',
    'hyperextension weighted': 'hyperextension-weighted',
    'hyperextension bodyweight': 'hyperextension-bw',
    # v4 ve daha eski havuzdaki açık, anlamı kesin isim varyasyonları.
    'barbell bench press': 'bench-press',
    'flat bench press': 'bench-press',
    'db bench press': 'dumbbell-bench-press',
    'incline barbell bench press': 'incline-bench-press',
    'incline db press': 'incline-dumbbell-press',
    'machine chest press': 'chest-press-machine',
    'push up': 'push-ups-bw',
    'push ups': 'push-ups-bw',
    'weighted push up': 'push-ups-weighted',
    'weighted push ups': 'push-ups-weighted',
    'lat pulldown': 'lat-pull-down',
    'lat pull down': 'lat-pull-down',
    'seated cable row': 'seated-row',
    'barbell bent over row': 'bent-over-row',
    'inverted rows': 'inverted-row-bw',
    'barbell squat': 'squat',
    'back squat': 'squat',
    'front barbell squat': 'front-squat',
    'bulgarian squat': 'bulgarian-split-squad',
    'bss': 'bulgarian-split-squad',
    'weight_bulgarian_split': 'bulgarian-split-squad',
    'weight bulgarian split': 'bulgarian-split-squad',
    'weight-bulgarian-split': 'bulgarian-split-squad',
    'bulgarian split squat weighted': 'bulgarian-split-squad',
    'bulgarian split squat bodyweight': 'bulgarian-split-squat-bw',
    'romanian dead lift': 'romanian-deadlift',
    'rdl': 'romanian-deadlift',
    'leg extensions': 'leg-extension',
    'seated leg curl': 'leg-curl',
    'lying leg curl': 'leg-curl',
    'hamstring curl': 'leg-curl',
    'calf raises bodyweight': 'calf-raises-bw',
    'military press': 'overhead-press',
    'barbell overhead press': 'overhead-press',
    'lateral raise': 'lateral-raises',
    'side lateral raise': 'lateral-raises',
    'triceps pushdown': 'tricep-push-down',
    'cable tricep pushdown': 'tricep-push-down',
    'rope pushdown': 'tricep-push-down',
    'dumbbell curl': 'bicep-curl',
    'barbell curl': 'bicep-curl',
    'cable curl': 'cable-bicep-curl',
    # 26 geçmiş kaydı kapsayan kesin ad varyasyonları (salt-okunur çözümleme için).
    'upright row': 'upright-row',
    'upright rows': 'upright-row',
    'single arm low row': 'single-arm-low-row',
    'single arm low rows': 'single-arm-low-row',
    'cable row': 'seated-row',
    'cable rows': 'seated-row',
    'cable upper back low row': 'cable-upper-back-low-row',
    'cable upper back low rows': 'cable-upper-back-low-row',
    'cable upper-back low row': 'cable-upper-back-low-row',
    'cable upper-back low rows': 'cable-upper-back-low-row',
    'cable upper back row': 'cable-upper-back-low-row',
    'cable upper-back row': 'cable-upper-back-low-row',
    'upper back cable low row': 'cable-upper-back-low-row',
    'upper-back cable low row': 'cable-upper-back-low-row',
    'upper back low row': 'cable-upper-back-low-row',
    'upper back low rows': 'cable-upper-back-low-row',
    'upper-back low row': 'cable-upper-back-low-row',
    'upper-back low rows': 'cable-upper-back-low-row',
    'single arm pulldown': 'single-arm-pulldown',
    'single arm pulldowns': 'single-arm-pulldown',
    'single arm pull down': 'single-arm-pulldown',
    'single arm pull downs': 'single-arm-pulldown',
    'skull crusher': 'skull-crushers',
    'skull crushers': 'skull-crushers',
    'lateral raises': 'lateral-raises',
    'reverse fly': 'dumbbell-rear-delt-fly',
    'reverse flies': 'dumbbell-rear-delt-fly',
    'back fly': 'dumbbell-rear-delt-fly',
    'back flies': 'dumbbell-rear-delt-fly',
    'rear delt fly': 'dumbbell-rear-delt-fly',
    'rear delt flies': 'dumbbell-rear-delt-fly',
    'dumbbell shruge': 'dumbbell-shrugs',
    'dumbbell shrug': 'dumbbell-shrugs',
    'shoulder press': 'shoulder-press',
    'triceps extens': 'triceps-extension',
    'triceps extension': 'triceps-extension',
    'preacher curl': 'preacher-curl',
    'cable lateral raise': 'cable-lateral-raises',
    'cable lateral raises': 'cable-lateral-raises',
    'overhead triceps extension': 'overhead-tricep-extension',
    'dumbbell low row': 'dumbbell-low-row',
    'barbell shruge': 'barbell-shrugs',
    'ez bar preacher curl': 'preacher-curl-z-bar',
    # Rotator / skapula / gluteal katalog isim varyasyonları.
    'shoulder cable external rotation': 'cable-shoulder-external-rotation',
    'cable shoulder external rotations': 'cable-shoulder-external-rotation',
    'shoulder cable internal rotation': 'cable-shoulder-internal-rotation',
    'cable shoulder internal rotations': 'cable-shoulder-internal-rotation',
    'cable 90 90 external rotation': 'cable-90-90-external-rotation',
    'cable y raises': 'cable-y-raise',
    'cable y raise': 'cable-y-raise',
    'cable serratus punches': 'cable-serratus-punch',
    'machine scapular retraction': 'machine-scapular-retraction',
    'scapular retraction machine': 'machine-scapular-retraction',
    'machine scapular retractions': 'machine-scapular-retraction',
    'chest supported dumbbell scapular retraction': 'chest-supported-dumbbell-scapular-retraction',
    'chest supported dumbbell scapular retractions': 'chest-supported-dumbbell-scapular-retraction',
    'prone dumbbell scapular retraction': 'chest-supported-dumbbell-scapular-retraction',
    'cable serratus punch': 'cable-serratus-punch',
    'cable scapular retractions': 'cable-scapular-retraction',
    'cable scapular retraction': 'cable-scapular-retraction',
    'cable hip abduction': 'cable-hip-abduction',
    'cable hip extensions': 'cable-hip-extension',
    'cable hip extension': 'cable-hip-extension',
    'cable hip external rotations': 'cable-hip-external-rotation',
    'cable hip external rotation': 'cable-hip-external-rotation',
    'cable hip internal rotations': 'cable-hip-internal-rotation',
    'cable hip internal rotation': 'cable-hip-internal-rotation',
    'adductor machine': 'machine-adductor',
    'adduction machine': 'machine-adductor',
    'seated adductor machine': 'machine-adductor',
    'hip adduction machine': 'machine-adductor',
    'seated hip adduction machine': 'machine-adductor',
    'seated hip adduction': 'machine-adductor',
    'cable hip adduction': 'cable-hip-adduction',
    'cable hip adductions': 'cable-hip-adduction',
    'cable adduction': 'cable-hip-adduction',
    'barbell upright row': 'upright-row',
    'upright row z bar': 'upright-row',
    'z bar upright row': 'upright-row',
    'ez bar upright row': 'upright-row',
    'cable upright row': 'upright-row',
}
