"""
Hypertrophy-X PostgreSQL / Neon şeması.

JSON tabanlı uzman sistemi alanları TEXT olarak tutulur. Böylece SQLite ve
PostgreSQL aynı API sözleşmesini kullanır ve ileride yeni anket bölümleri şema
göçü gerektirmeden eklenebilir.
"""

POSTGRES_SCHEMA_STATEMENTS = (
    """
    CREATE TABLE IF NOT EXISTS users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username TEXT UNIQUE NOT NULL,
        password_hash TEXT NOT NULL DEFAULT '',
        password_salt TEXT NOT NULL DEFAULT '',
        age INTEGER NOT NULL DEFAULT 0,
        gender TEXT NOT NULL DEFAULT 'male',
        height DOUBLE PRECISION NOT NULL DEFAULT 170.0,
        weight DOUBLE PRECISION NOT NULL DEFAULT 70.0,
        fitness_level TEXT NOT NULL DEFAULT 'Beginner',
        goal TEXT NOT NULL DEFAULT 'bulk',
        days_per_week INTEGER NOT NULL DEFAULT 4,
        session_time_mins INTEGER NOT NULL DEFAULT 60,
        stagnation_detected INTEGER NOT NULL DEFAULT 0,
        custom_split TEXT NOT NULL DEFAULT '[]',
        dashboard_preferences TEXT NOT NULL DEFAULT '{}',
        daily_nutrition TEXT NOT NULL DEFAULT '{}',
        is_admin INTEGER NOT NULL DEFAULT 0,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS workouts (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        date TEXT NOT NULL,
        session_type TEXT NOT NULL,
        notes TEXT DEFAULT '',
        total_volume DOUBLE PRECISION NOT NULL DEFAULT 0,
        exercises TEXT NOT NULL DEFAULT '[]',
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    """,
    # Daha önceki sürümlerde oluşturulmuş users tabloları ile uyumluluk.
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS dashboard_preferences TEXT NOT NULL DEFAULT '{}'",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS daily_nutrition TEXT NOT NULL DEFAULT '{}'",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS is_admin INTEGER NOT NULL DEFAULT 0",
    """
    CREATE TABLE IF NOT EXISTS expert_profiles (
        user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
        goals_json TEXT NOT NULL DEFAULT '{}',
        doms_history_json TEXT NOT NULL DEFAULT '[]',
        constraints_json TEXT NOT NULL DEFAULT '[]',
        ui_preferences_json TEXT NOT NULL DEFAULT '{}',
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_workouts_user_date ON workouts (user_id, date DESC)",
)
